name: dartle
description: A simple build system written in Dart. Tasks are declared in a regular Dart file.
version: 0.7.0
homepage: https://github.com/renatoathaydes/dartle

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  meta: ^1.3.0-nullsafety.6
  ansicolor: 2.0.0-nullsafety.0
  logging: ^1.0.0
  crypto: ^3.0.0
  path: ^1.8.0-nullsafety.3
  collection: ^1.15.0-nullsafety.5
  actors: ^0.7.0-nullsafety.1

dev_dependencies:
  build_runner: ^1.11.5
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.9
  file: ^6.1.0
  mockito: ^5.0.0
  yaml: ^3.1.0

executables:
  dartle: