name: dartle
description: A simple build system written in Dart. Tasks are declared in a regular Dart file.
version: 0.5.1
homepage: https://github.com/renatoathaydes/dartle
author: renato <renato@athaydes.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  meta: ^1.1.7
  ansicolor: ^1.0.2
  logging: ^0.11.3+2
  crypto: ^2.1.2
  path: ^1.6.4
  collection: ^1.14.12
  actors: ^0.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  file: ^5.0.10
  mockito: ^4.1.1
  yaml: ^2.1.16

executables:
  dartle: