name: dartle
description: A simple build system written in Dart. Tasks are declared in a regular Dart file.
version: 0.14.0
homepage: https://github.com/renatoathaydes/dartle

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.0.0
  meta: ^1.3.0
  io: ^1.0.0
  logging: ^1.0.0
  crypto: ^3.0.0
  path: ^1.8.0
  collection: ^1.15.0
  actors: ^0.8.0
  structured_async: ^0.3.0
  clock: ^1.1.0
  file: ^6.1.0
  test_report_parser: ^1.1.0

dev_dependencies:
  test: ^1.16.8
  yaml: ^3.1.0
  lints: ^1.0.1

executables:
  dartle: