name: dartle
description: A simple build system written in Dart. Tasks are declared in a regular Dart file.
version: 0.8.0
homepage: https://github.com/renatoathaydes/dartle

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  meta: ^1.3.0
  ansicolor: ^2.0.1
  logging: ^1.0.0
  crypto: ^3.0.0
  path: ^1.8.0
  collection: ^1.15.0
  actors: ^0.7.0
  clock: ^1.1.0

dev_dependencies:
  build_runner: ^1.12.1
  pedantic: ^1.11.0
  test: ^1.16.8
  file: ^6.1.0
  yaml: ^3.1.0

executables:
  dartle: